### ISSUE TITLE
texpress.annotate_files not working as expected

### ISSUE THREAD

**Issue by rachaellturner** [SciBiteLabs/termite_toolkit#5]
Gives unexpected output:
`options = {"format": "medline.xml", "output": "jsonx", "bundle": "DrugApproval", "maxDocs": 10}
texpress_json_response = texpress.annotate_files(termite_home, input_file, options)
pprint(texpress_json_response)`

Gives expected output:
`t = texpress.TexpressRequestBuilder()

t.set_url(termite_home)
t.set_binary_content(input_file)
t.set_input_format("medline.xml")
t.set_output_format("jsonx")
t.set_bundle("DrugApproval")
t.set_max_docs(10)

texpress_response = t.execute(display_request=True)

pprint(texpress_response)`

**Comment by JMMull** [comment]
Resolved by rachel.
